# Generated by Django 6.0.6 on 2026-06-09 07:24

import apps.media_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(max_length=120, unique=True)),
                ('task_type', models.CharField(choices=[('EMAIL_SEND', '이메일 발송'), ('PDF_GENERATE', 'PDF 생성'), ('EXCEL_GENERATE', '엑셀 생성'), ('EXCEL_PARSE', '엑셀 파싱'), ('FILE_SCAN', '파일 검사'), ('DUE_NOTIFICATION', '마감 알림')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('STARTED', '시작'), ('SUCCESS', '성공'), ('FAILURE', '실패'), ('RETRY', '재시도')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.media_files.models.upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('IMAGE', '이미지'), ('EXCEL', '엑셀'), ('PDF', 'PDF'), ('ETC', '기타')], default='ETC', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('target_app', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_folder', models.CharField(default='uploads', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
