# Generated by Django 6.0.6 on 2026-06-09 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todos.todo'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'status'], name='todos_todo_user_id_c62cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['deadline_at'], name='todos_todo_deadlin_479c6e_idx'),
        ),
    ]
