# Generated by Django 6.0.6 on 2026-06-09 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('media_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.boardcomment'),
        ),
        migrations.AddField(
            model_name='boardfile',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_files.mediafile'),
        ),
        migrations.AddField(
            model_name='boardfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='boards.boardpost'),
        ),
        migrations.AddField(
            model_name='boardfile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='boards.boardpost'),
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boards.boardpost'),
        ),
        migrations.AddIndex(
            model_name='boardpost',
            index=models.Index(fields=['board_type', 'is_deleted'], name='boards_boar_board_t_e5f60b_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpost',
            index=models.Index(fields=['author', 'created_at'], name='boards_boar_author__3d06d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardlike',
            unique_together={('post', 'user')},
        ),
    ]
