# Generated by Django 6.0.6 on 2026-06-09 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', '요청됨'), ('ASSIGNED', '담당자 지정'), ('IN_PROGRESS', '진행중'), ('ON_HOLD', '보류'), ('COMPLETED', '완료 요청'), ('APPROVED', '승인 완료'), ('REJECTED', '반려'), ('CANCELED', '취소')], default='REQUESTED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('NORMAL', '보통'), ('HIGH', '높음'), ('URGENT', '긴급')], default='NORMAL', max_length=20)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_work_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='work_requests.workrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_files.mediafile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='work_requests.workrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['requester', 'status'], name='work_reques_request_a4f119_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['assignee', 'status'], name='work_reques_assigne_56c06f_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['deadline_at'], name='work_reques_deadlin_07d184_idx'),
        ),
    ]
