# Generated by Django 6.0.6 on 2026-06-09 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_files', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereceipt',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_files.mediafile'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['writer', 'report_type', 'report_date'], name='reports_rep_writer__07ce13_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['approver', 'status'], name='reports_rep_approve_ead804_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['report', 'expense_date', 'category'], name='reports_exp_report__93c67d_idx'),
        ),
    ]
