# Generated by Django 6.0.6 on 2026-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('schedule_type', models.CharField(choices=[('PERSONAL', '개인'), ('WORK', '업무'), ('MEETING', '회의'), ('TODO', '할일'), ('WORK_REQUEST', '업무요청')], default='PERSONAL', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_shared', models.BooleanField(default=False)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(default='#4285F4', max_length=20)),
                ('is_all_day', models.BooleanField(default=False)),
                ('repeat_type', models.CharField(choices=[('NONE', '반복 없음'), ('DAILY', '매일'), ('WEEKLY', '매주'), ('MONTHLY', '매월'), ('YEARLY', '매년')], default='NONE', max_length=20)),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['start_at', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.CharField(choices=[('PENDING', '대기'), ('ACCEPTED', '참석'), ('DECLINED', '불참'), ('TENTATIVE', '미정')], default='PENDING', max_length=20)),
            ],
        ),
    ]
