# Generated by Django 6.0.6 on 2026-06-09 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleparticipant',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='scheduleparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['owner', 'start_at'], name='schedules_s_owner_i_1f4cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_at', 'end_at'], name='schedules_s_start_a_79ab9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleparticipant',
            unique_together={('schedule', 'user')},
        ),
    ]
