# Generated by Django 6.0.6 on 2026-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('WORK_REQUEST', '업무요청'), ('TODO', '할일'), ('SCHEDULE', '일정'), ('BOARD', '게시판'), ('REPORT', '보고서'), ('EXPENSE', '경비'), ('SYSTEM', '시스템')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_request_enabled', models.BooleanField(default=True)),
                ('todo_enabled', models.BooleanField(default=True)),
                ('schedule_enabled', models.BooleanField(default=True)),
                ('board_enabled', models.BooleanField(default=True)),
                ('report_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('realtime_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
